##  This juypeter notbook based on numpy youtube tutorial
* Help markdown script is used in github
- this cell is markdown script

In [9]:
import numpy as np

#why numpy? because it's faster than list, numpy utilize contiguouse memory.
arr1 = np.array([[[1.0,2.0,3.0],[4,5,6]] , [[7,8,9],[0,0,0]]] , dtype = 'float32') #floats
print(arr1)
print(arr1.shape)
print(arr1.dtype)
print(arr1[0][0][0].nbytes) #print the size of single element
print(f"{arr1[:,:,0: :2]}\n---------------") #print all elements but jumb by two
print(f"{arr1[:,:,-1: :-2]}\n---------------") #print all elements but jumb by two backward
print(f"{arr1[:,:,0]}\n---------------") #print all first colmn

[[[1. 2. 3.]
  [4. 5. 6.]]

 [[7. 8. 9.]
  [0. 0. 0.]]]
(2, 2, 3)
float32
4
[[[1. 3.]
  [4. 6.]]

 [[7. 9.]
  [0. 0.]]]
---------------
[[[3. 1.]
  [6. 4.]]

 [[9. 7.]
  [0. 0.]]]
---------------
[[1. 4.]
 [7. 0.]]
---------------


# Difference matrices
* np.zeros( (size tuble) )
* np.one( (size tuble) )
* np.full( (size tuble) , value , dtype = 'int64' )
* np.full_like( arr1 , 55 )
* np.random.rand(4,2,3) 
* np.random.randomsample(arr1.shape)

In [28]:
print( f"{np.zeros((3,3))}" )
print( f"{np.ones((3,3))}" )
print( f"{np.full((3,3) , 69 , dtype = 'float64')}" )
print( f"{np.full_like(arr1, 55) }" )
print( f"{np.random.rand(4,2,3) }" )


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[69. 69. 69.]
 [69. 69. 69.]
 [69. 69. 69.]]
[[[55. 55. 55.]
  [55. 55. 55.]]

 [[55. 55. 55.]
  [55. 55. 55.]]]
[[[0.25205648 0.33119954 0.87668045]
  [0.78823201 0.22929617 0.08100779]]

 [[0.31605485 0.50215462 0.79992741]
  [0.28780637 0.71712535 0.4930311 ]]

 [[0.00440271 0.82096155 0.12559444]
  [0.48221134 0.74656849 0.58557215]]

 [[0.49840169 0.65973592 0.73530208]
  [0.77908609 0.88173427 0.57140106]]]
[[[0.1286414  0.4955119  0.11393157]
  [0.60898051 0.55685623 0.5508538 ]]

 [[0.86297667 0.82170493 0.22673113]
  [0.63748307 0.59697544 0.78872627]]]


In [39]:
print( f"{np.random.random_sample(arr1.shape) }" )
print( f"{np.random.randint(-50,5,arr1.shape) }" )
print( f"{np.identity( 5 ) }" )
print( f"{np.repeat(arr1 , 3) }" )
print( f"{np.repeat(arr1 , 3 , axis = 0) }" )
print( f"{np.repeat(arr1 , 3 , axis = 1) }" )

[[[0.2077368  0.76752537 0.30263395]
  [0.98440485 0.35892762 0.23440107]]

 [[0.31308262 0.90866551 0.96949489]
  [0.31216129 0.15910614 0.11804916]]]
[[[-34 -35 -18]
  [-18 -47 -12]]

 [[-25 -47  -7]
  [-12 -47  -9]]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 2. 2. 2. 3. 3. 3. 4. 4. 4. 5. 5. 5. 6. 6. 6. 7. 7. 7. 8. 8. 8.
 9. 9. 9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[1. 2. 3.]
  [4. 5. 6.]]

 [[1. 2. 3.]
  [4. 5. 6.]]

 [[1. 2. 3.]
  [4. 5. 6.]]

 [[7. 8. 9.]
  [0. 0. 0.]]

 [[7. 8. 9.]
  [0. 0. 0.]]

 [[7. 8. 9.]
  [0. 0. 0.]]]
[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]
  [4. 5. 6.]
  [4. 5. 6.]
  [4. 5. 6.]]

 [[7. 8. 9.]
  [7. 8. 9.]
  [7. 8. 9.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [57]:
import numpy as np
# Quiz
a = np.ones( (5,5) )
b = np.zeros( (3,3) )
b[1,1] = 9
a[1:-1,1:-1] = b.copy() #be careful when you copy array
print(f"{a}")
print(f"Number of arr2 colomns = {a.shape[1]}")
print(f"Number of arr2 raws = {a.shape[0]}")

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Number of arr2 colomns = 5
Number of arr2 raws = 5


# Mathematics

In [86]:
a = np.array([[1,2,3,4]])
b = a + 2
c = a ** 2
d = a / 2
e = np.sin(a)
f = np.sum(a , axis = 1)
g = np.max(a, axis = 1)
print(f"{a}")
print(f"{b}")
print(f"{c}")
print(f"{d}")
print(f"{e}")
print(f"sum of a at vertical axis {f}")
print(f"maximum element value of a at vertical axis {g}")

print(f"Number of arr2 colomns = {a.shape[1]}")
print(f"Number of arr2 raws = {a.shape[0]}")

[[1 2 3 4]]
[[3 4 5 6]]
[[ 1  4  9 16]]
[[0.5 1.  1.5 2. ]]
[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]]
sum of a at vertical axis [10]
maximum element value of a at vertical axis [4]
Number of arr2 colomns = 4
Number of arr2 raws = 1


# Linear Algebra



In [88]:
a = np.ones( (3,2) )
b = np.full( (4,3) , 5)
c = np.matmul(b,a)
d = c.reshape( (2, 4))
print(f"{a}")
print(f"{b}")
print(f"b × a =\n{c}")
print(f"Reshape b x a =\n{d}")
print(f"Determnenant of identity matrix multiplied by 2 = {np.linalg.det(np.identity(5) * 2)}") #find the determenant

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
b × a =
[[15. 15.]
 [15. 15.]
 [15. 15.]
 [15. 15.]]
Reshape b x a =
[[15. 15. 15. 15.]
 [15. 15. 15. 15.]]
Determnenant of identity matrix multiplied by 2 = 32.0


# Linear Algebra
* Determentant
* Trace
* Singluar vector decomposition
* Eigen values
* Matrix norm
* inverse
* est...


In [96]:
v1 = np.ones((1,4))
v2 = np.zeros( (1,4) )
a = np.vstack([v1,v2] )
b = np.hstack([v1,v2] )

print(f"{a}")
print(f"{b}")
print(f"{a>=1}")


[[1. 1. 1. 1.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0.]]
[[ True  True  True  True]
 [False False False False]]
